/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 phantoms.glb --transform
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

export function Robot(props) {
  const { nodes, materials } = useGLTF('./models/car/scene.gltf')
  const robot = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(robot.current.rotation, {y: 3}, 2)
    .to(robot.current.position, {x: 1}, 2)

    .to(robot.current.rotation, {y: 1}, 6)   
    .to(robot.current.position, {x: -2}, 5)

    .to(robot.current.rotation, {y: 0}, 11)
    .to(robot.current.rotation, {x: 1}, 11)
    .to(robot.current.position, {x: 0}, 11)

    .to(robot.current.rotation, {y: 0}, 13)
    .to(robot.current.rotation, {x: 1}, 13)
    .to(robot.current.position, {x: 0}, 13)

    .to(robot.current.rotation, {y: 2}, 16)
    .to(robot.current.rotation, {x: 1}, 16)
    .to(robot.current.position, {x: 0}, 16)

    // .to(robot.current.rotation, {y: 0}, 20)
    // .to(robot.current.rotation, {x: 0}, 20)
    // .to(robot.current.position, {x: 0}, 20)

  },[])
  
  return (
    <group {...props} dispose={null} ref={robot}>

      <group  position={[-0.21, 0.16, 0.37]} rotation={[0, 1, 0]} scale={0.014}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_hood_b_gallardo_badges_0.geometry} material={materials.gallardo_badges} />
          <mesh geometry={nodes.gallardo_hood_b_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={74.699}>
          <mesh geometry={nodes.gallardo_steeringwheel_support_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_steeringwheel_support_gallardo_cockpit_0.geometry} material={materials.gallardo_cockpit} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[41.858, 40.623, 40.623]}>
          <mesh geometry={nodes.gallardo_engine_biturbo_airfilter_gallardo_turbo_gray_0.geometry} material={materials.gallardo_turbo_gray} />
          <mesh geometry={nodes.gallardo_engine_biturbo_airfilter_gallardo_turbo_intake_0.geometry} material={materials.gallardo_turbo_intake} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[41.858, 40.623, 40.623]}>
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_metal_0.geometry} material={materials.gallardo_metal} />
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_turbo_blackexit_0.geometry} material={materials.gallardo_turbo_blackexit} />
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_turbo_gold_0.geometry} material={materials.gallardo_turbo_gold} />
          <mesh geometry={nodes.gallardo_engine_biturbo_gallardo_turbo_blackcomp_0.geometry} material={materials.gallardo_turbo_blackcomp} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_tankintake_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
          <mesh geometry={nodes.gallardo_tankintake_gallardo_turbo_intake_0.geometry} material={materials.gallardo_turbo_intake} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_tailgate_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_tailgate_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_tailgate_gallardo_glass_0.geometry} material={materials.gallardo_glass} />
        </group>
        <group position={[35.977, 69.731, 46.048]} rotation={[-1.322, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_steer_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
          <mesh geometry={nodes.gallardo_steer_gallardo_steeringwheel_0.geometry} material={materials.gallardo_steeringwheel} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_spoiler_LW2_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_spoiler_LW2_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_spoiler_LW2_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_spoiler_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_spoiler_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_spoiler_gallardo_chmsl_0.geometry} material={materials.gallardo_chmsl} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_shifter_A_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_shifter_A_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_seat_FR_sl_gallardo_alcantara_0.geometry} material={materials.gallardo_alcantara} />
          <mesh geometry={nodes.gallardo_seat_FR_sl_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_seat_FL_sl_gallardo_alcantara_0.geometry} material={materials.gallardo_alcantara} />
          <mesh geometry={nodes.gallardo_seat_FL_sl_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_mirror_R_cf_mirror_0.geometry} material={materials.mirror} />
          <mesh geometry={nodes.gallardo_mirror_R_cf_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_mirror_L_cf_mirror_0.geometry} material={materials.mirror} />
          <mesh geometry={nodes.gallardo_mirror_L_cf_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_intmirror_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_intmirror_gallardo_alcantara_0.geometry} material={materials.gallardo_alcantara} />
          <mesh geometry={nodes.gallardo_intmirror_mirror_0.geometry} material={materials.mirror} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_headlight_R_gallardo_lights_0.geometry} material={materials.gallardo_lights} />
          <mesh geometry={nodes.gallardo_headlight_R_gallardo_headlight_0.geometry} material={materials.gallardo_headlight} />
          <mesh geometry={nodes.gallardo_headlight_R_gallardo_runninglight_0.geometry} material={materials.gallardo_runninglight} />
          <mesh geometry={nodes.gallardo_headlight_R_gallardo_signal_R_0.geometry} material={materials.gallardo_signal_R} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_headlight_L_gallardo_lights_0.geometry} material={materials.gallardo_lights} />
          <mesh geometry={nodes.gallardo_headlight_L_gallardo_signal_L_0.geometry} material={materials.gallardo_signal_L} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_gauges_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} />
          <mesh geometry={nodes.gallardo_gauges_gallardo_lcd_0.geometry} material={materials.gallardo_lcd} />
          <mesh geometry={nodes.gallardo_gauges_gallardo_lcd4_0.geometry} material={materials.gallardo_lcd4} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_front_support_compact_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_front_support_compact_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_front_support_compact_gallardo_chassis_0.geometry} material={materials.gallardo_chassis} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_fenderflare_RR_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_fenderflare_RR_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_fenderflare_RL_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_fenderflare_RL_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_fenderflare_FR_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_fenderflare_FR_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_fenderflare_FR_gallardo_badges_0.geometry} material={materials.gallardo_badges} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_fenderflare_FL_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_fenderflare_FL_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_fenderflare_FL_gallardo_badges_0.geometry} material={materials.gallardo_badges} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_fender_R_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_fender_R_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_exhaust_quad_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_exhaust_quad_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_exhaust_header_turbo_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_exhaust_header_turbo_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_exhaust_header_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
          <mesh geometry={nodes.gallardo_exhaust_header_gallardo_turbo_intake_0.geometry} material={materials.gallardo_turbo_intake} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_engine_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_engine_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
          <mesh geometry={nodes.gallardo_engine_gallardo_turbo_gray_0.geometry} material={materials.gallardo_turbo_gray} />
          <mesh geometry={nodes.gallardo_engine_gallardo_metal_0.geometry} material={materials.gallardo_metal} />
          <mesh geometry={nodes.gallardo_engine_gallardo_nodam_0.geometry} material={materials.gallardo_nodam} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_doorpanel_R_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_doorpanel_R_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
          <mesh geometry={nodes.gallardo_doorpanel_R_gallardo_leather_quilted_0.geometry} material={materials.gallardo_leather_quilted} />
          <mesh geometry={nodes.gallardo_doorpanel_R_gallardo_mesh_0.geometry} material={materials.gallardo_mesh} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_doorpanel_L_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_doorpanel_L_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
          <mesh geometry={nodes.gallardo_doorpanel_L_gallardo_leather_quilted_0.geometry} material={materials.gallardo_leather_quilted} />
          <mesh geometry={nodes.gallardo_doorpanel_L_gallardo_mesh_0.geometry} material={materials.gallardo_mesh} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_doorlivery_R_sl_gallardo_flag_it_0.geometry} material={materials.gallardo_flag_it} />
          <mesh geometry={nodes.gallardo_doorlivery_R_sl_gallardo_badge_sl_0.geometry} material={materials.gallardo_badge_sl} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_doorlivery_L_sl_gallardo_flag_it_0.geometry} material={materials.gallardo_flag_it} />
          <mesh geometry={nodes.gallardo_doorlivery_L_sl_gallardo_badge_sl_0.geometry} material={materials.gallardo_badge_sl} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_door_R_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_door_R_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_door_R_gallardo_alcantara_0.geometry} material={materials.gallardo_alcantara} />
          <mesh geometry={nodes.gallardo_door_R_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_door_L_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_door_L_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_door_L_gallardo_alcantara_0.geometry} material={materials.gallardo_alcantara} />
          <mesh geometry={nodes.gallardo_door_L_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_dash_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_dash_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
          <mesh geometry={nodes.gallardo_dash_gallardo_cockpit_0.geometry} material={materials.gallardo_cockpit} />
          <mesh geometry={nodes.gallardo_dash_gallardo_leather_stitching_white_0.geometry} material={materials.gallardo_leather_stitching_white} />
          <mesh geometry={nodes.gallardo_dash_gallardo_cockbadge_0.geometry} material={materials.gallardo_cockbadge} />
          <mesh geometry={nodes.gallardo_dash_gallardo_cockpit_on_0.geometry} material={materials.gallardo_cockpit_on} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_bumper_R_LW_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_bumper_R_LW_gallardo_turbo_gray_0.geometry} material={materials.gallardo_turbo_gray} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_bumper_F_LW_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_bumper_F_LW_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} />
          <mesh geometry={nodes.gallardo_bumper_F_LW_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} />
          <mesh geometry={nodes.gallardo_bumper_F_LW_gallardo_cf_0.geometry} material={materials.gallardo_cf} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.gallardo_body_gallardo_misc_0.geometry} material={materials.gallardo_misc} />
          <mesh geometry={nodes.gallardo_body_gallardo_paint_0.geometry} material={materials.gallardo_paint} />
          <mesh geometry={nodes.gallardo_body_gallardo_leather_0.geometry} material={materials.gallardo_leather} />
          <mesh geometry={nodes.gallardo_body_gallardo_alcantara_0.geometry} material={materials.gallardo_alcantara} />
          <mesh geometry={nodes.gallardo_body_gallardo_chassis_0.geometry} material={materials.gallardo_chassis} />
          <mesh geometry={nodes.gallardo_body_mirror_0.geometry} material={materials.mirror} />
          <mesh geometry={nodes.gallardo_body_gallardo_leather_stitching_black_0.geometry} material={materials.gallardo_leather_stitching_black} />
          <mesh geometry={nodes.gallardo_body_gallardo_carpet_0.geometry} material={materials.gallardo_carpet} />
          <mesh geometry={nodes.gallardo_body_gallardo_engine_0.geometry} material={materials.gallardo_engine} />
        </group>
        <group position={[85.34, 37.195, 128.827]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={85.538}>
          <mesh geometry={nodes['3_Wheel_Scene_-_Root001_0'].geometry} material={materials['Scene_-_Root.001']} />
          <mesh geometry={nodes['3_Wheel_amdb11_brake001_0'].geometry} material={materials['amdb11_brake.001']} />
          <mesh geometry={nodes['3_Wheel_amdb11_misc_chrome001_0'].geometry} material={materials['amdb11_misc_chrome.001']} />
          <mesh geometry={nodes['3_Wheel_amdb11_misc001_0'].geometry} material={materials['amdb11_misc.001']} />
          <mesh geometry={nodes['3_Wheel_amdb11_caliper001_0'].geometry} material={materials['amdb11_caliper.001']} />
        </group>
        <group position={[85.34, 37.195, -126.496]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={85.538}>
          <mesh geometry={nodes['3_Wheel001_Scene_-_Root001_0'].geometry} material={materials['Scene_-_Root.001']} />
          <mesh geometry={nodes['3_Wheel001_amdb11_brake001_0'].geometry} material={materials['amdb11_brake.001']} />
          <mesh geometry={nodes['3_Wheel001_amdb11_misc_chrome001_0'].geometry} material={materials['amdb11_misc_chrome.001']} />
          <mesh geometry={nodes['3_Wheel001_amdb11_misc001_0'].geometry} material={materials['amdb11_misc.001']} />
          <mesh geometry={nodes['3_Wheel001_amdb11_caliper001_0'].geometry} material={materials['amdb11_caliper.001']} />
        </group>
        <group position={[-85.021, 37.195, 128.827]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-85.538, 85.538, 85.538]}>
          <mesh geometry={nodes['3_Wheel002_Scene_-_Root001_0'].geometry} material={materials['Scene_-_Root.001']} />
          <mesh geometry={nodes['3_Wheel002_amdb11_brake001_0'].geometry} material={materials['amdb11_brake.001']} />
          <mesh geometry={nodes['3_Wheel002_amdb11_misc_chrome001_0'].geometry} material={materials['amdb11_misc_chrome.001']} />
          <mesh geometry={nodes['3_Wheel002_amdb11_misc001_0'].geometry} material={materials['amdb11_misc.001']} />
          <mesh geometry={nodes['3_Wheel002_amdb11_caliper001_0'].geometry} material={materials['amdb11_caliper.001']} />
        </group>
        <group position={[-85.021, 37.195, -126.496]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-85.538, 85.538, 85.538]}>
          <mesh geometry={nodes['3_Wheel003_Scene_-_Root001_0'].geometry} material={materials['Scene_-_Root.001']} />
          <mesh geometry={nodes['3_Wheel003_amdb11_brake001_0'].geometry} material={materials['amdb11_brake.001']} />
          <mesh geometry={nodes['3_Wheel003_amdb11_misc_chrome001_0'].geometry} material={materials['amdb11_misc_chrome.001']} />
          <mesh geometry={nodes['3_Wheel003_amdb11_misc001_0'].geometry} material={materials['amdb11_misc.001']} />
          <mesh geometry={nodes['3_Wheel003_amdb11_caliper001_0'].geometry} material={materials['amdb11_caliper.001']} />
        </group>
        <mesh geometry={nodes.gallardo_backlight_tinted_gallardo_glass_tinted_0.geometry} material={materials.gallardo_glass_tinted} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_doorglass_L_tinted_gallardo_glass_tinted_0.geometry} material={materials.gallardo_glass_tinted} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_doorglass_R_tinted_gallardo_glass_tinted_0.geometry} material={materials.gallardo_glass_tinted} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_sideglass_L_tinted_gallardo_glass_tinted_0.geometry} material={materials.gallardo_glass_tinted} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_sideglass_R_tinted_gallardo_glass_tinted_0.geometry} material={materials.gallardo_glass_tinted} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_windshield_tinted_gallardo_glass_tinted_0.geometry} material={materials.gallardo_glass_tinted} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_comodo_gallardo_cockpit_0.geometry} material={materials.gallardo_cockpit} rotation={[-Math.PI / 2, 0, 0]} scale={74.699} />
        <mesh geometry={nodes.gallardo_wipers_gallardo_misc_0.geometry} material={materials.gallardo_misc} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_wheel_02a_19x11_gallardo_wheel_01a_0.geometry} material={materials.gallardo_wheel_01a} position={[85.34, 37.195, 128.827]} rotation={[-Math.PI / 2, 0, 0]} scale={108.08} />
        <mesh geometry={nodes.gallardo_taillightglass_R_gallardo_glass_0.geometry} material={materials.gallardo_glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_taillightglass_L_gallardo_glass_0.geometry} material={materials.gallardo_glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_stockintake_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_skirtaddons_sl_gallardo_cf_0.geometry} material={materials.gallardo_cf} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_shiftgate_M_gallardo_leather_0.geometry} material={materials.gallardo_leather} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_shifter_M_gallardo_metal_0.geometry} material={materials.gallardo_metal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_screen_gallardo_screen_0.geometry} material={materials.gallardo_screen} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_rear_support_tube_gallardo_turbo_black_0.geometry} material={materials.gallardo_turbo_black} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_paddles_gallardo_leather_0.geometry} material={materials.gallardo_leather} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_needle_watertemp_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} position={[50.629, 72.265, 68.21]} rotation={[-1.669, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_needle_tacho_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} position={[44.386, 76.618, 72.45]} rotation={[-1.799, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_needle_speedo_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} position={[27.61, 76.618, 72.555]} rotation={[-1.897, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_needle_oiltemp_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} position={[-0.001, 77.984, 94.724]} rotation={[-1.865, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_needle_oilpressure_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} position={[7.978, 78.006, 94.637]} rotation={[-1.826, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_needle_fuel_gallardo_gauges_0.geometry} material={materials.gallardo_gauges} position={[21.401, 72.266, 68.391]} rotation={[-1.784, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_logo_R_gallardo_badges_0.geometry} material={materials.gallardo_badges} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_lettering_body_gallardo_badges_0.geometry} material={materials.gallardo_badges} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_headlightglass_R_gallardo_glass_0.geometry} material={materials.gallardo_glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_headlightglass_L_gallardo_glass_0.geometry} material={materials.gallardo_glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_gaugeglass_gallardo_glass_0.geometry} material={materials.gallardo_glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_gaspedal_gallardo_leather_0.geometry} material={materials.gallardo_leather} position={[17.842, 24.9, 101.524]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_fender_L_gallardo_paint_0.geometry} material={materials.gallardo_paint} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_clutchpedal_gallardo_leather_0.geometry} material={materials.gallardo_leather} position={[38.152, 57.666, 117.753]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_bumper_R_LW_mesh_gallardo_turbo_matblack_0.geometry} material={materials.gallardo_turbo_matblack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_bumper_R_LW_diffuser_gallardo_cf_0.geometry} material={materials.gallardo_cf} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_bumper_F_LW_valance_gallardo_cf_0.geometry} material={materials.gallardo_cf} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_brakepedal_M_gallardo_leather_0.geometry} material={materials.gallardo_leather} position={[29.806, 57.661, 117.75]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_brakepedal_A_gallardo_leather_0.geometry} material={materials.gallardo_leather} position={[34.515, 57.666, 117.754]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_wheel_02a_19x11001_gallardo_wheel_01a_0.geometry} material={materials.gallardo_wheel_01a} position={[85.34, 37.195, -126.496]} rotation={[-Math.PI / 2, 0, 0]} scale={108.08} />
        <mesh geometry={nodes.gallardo_wheel_02a_19x11002_gallardo_wheel_01a_0.geometry} material={materials.gallardo_wheel_01a} position={[-85.021, 37.195, 128.827]} rotation={[-Math.PI / 2, 0, 0]} scale={[-108.08, 108.08, 108.08]} />
        <mesh geometry={nodes.gallardo_wheel_02a_19x11003_gallardo_wheel_01a_0.geometry} material={materials.gallardo_wheel_01a} position={[-85.021, 37.195, -126.496]} rotation={[-Math.PI / 2, 0, 0]} scale={[-108.08, 108.08, 108.08]} />
        <mesh geometry={nodes.gallardo_taillight_R_gallardo_taillight_L001_0.geometry} material={materials['gallardo_taillight_L.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.gallardo_taillight_L_gallardo_taillight_L001_0.geometry} material={materials['gallardo_taillight_L.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/car/scene.gltf')
